export const PARENT_ALLOWED_CHILD_CATEGORIES = {
  UL: new Set(["Flow content"]),
  OL: new Set(["Flow content"]),
  DL: new Set(["Flow content"]),
  SELECT: new Set(["Phrasing content", "Metadata content"]),
  TABLE: new Set(["Flow content"]),
  THEAD: new Set(["Flow content"]),
  TBODY: new Set(["Flow content"]),
  TFOOT: new Set(["Flow content"]),
  COLGROUP: new Set(["Metadata content"]),
  TR: new Set(["Flow content"]),
  HEAD: new Set(["Metadata content"]),
  OPTGROUP: new Set(["Phrasing content"]),
  A: new Set(["Phrasing content"]),
  BUTTON: new Set(["Phrasing content"]),
  P: new Set(["Phrasing content"]),
  LI: new Set(["Flow content"]),
  DIV: new Set(["Flow content"]),
  SECTION: new Set(["Flow content"]),
  ARTICLE: new Set(["Flow content"]),
  NAV: new Set(["Flow content"]),
  HEADER: new Set(["Flow content"]),
  FOOTER: new Set(["Flow content"]),
  ASIDE: new Set(["Flow content"]),
  MAIN: new Set(["Flow content"]),
  BLOCKQUOTE: new Set(["Flow content"]),
  SPAN: new Set(["Phrasing content"]),
  EM: new Set(["Phrasing content"]),
  STRONG: new Set(["Phrasing content"]),
  SMALL: new Set(["Phrasing content"]),
  MARK: new Set(["Phrasing content"]),
  SUB: new Set(["Phrasing content"]),
  SUP: new Set(["Phrasing content"]),
};

// Исключения — запрещённые дочерние для родителя
export const PARENT_CHILD_EXCEPTIONS = {
  A: new Set(["A"]),
  BUTTON: new Set(["BUTTON"]),
  LABEL: new Set(["LABEL"]),
  FORM: new Set(["FORM"]),
  P: new Set([
    "DIV",
    "SECTION",
    "ARTICLE",
    "HEADER",
    "FOOTER",
    "NAV",
    "ASIDE",
    "MAIN",
    "TABLE",
    "UL",
    "OL",
    "FORM",
  ]),
};
